StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{650CA5CD89CF3797}" {
   Id "MFN-IdentitySelector"
   Target_en_us "Identity Selector"
   ActorGender NONE
   Modified 1695328440
   Author "muffi"
   LastChanged "muffi"
  }
  CustomStringTableItem "{650CA5CDF08E4270}" {
   Id "MFN-OpenIdentitySelector"
   Target_en_us "Open Identity Selector"
   Modified 1695328443
   Author "muffi"
   LastChanged "muffi"
  }
 }
}